version: "3"
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    user: 1000:1000
    ports:
      - 127.0.0.1:9980:8080 
    volumes:
      - vw-data:/data
    environment:
      - SIGNUPS_ALLOWED=false
      - ROCKET_PORT=8080
      - EXTENDED_LOGGING=true
      - ORG_EVENTS_ENABLED=true
      - LOG_FILE=/data/vaultwarden.log
      - DOMAIN=${VAULTWARDEN_PATH}
      - LOG_LEVEL=trace
    restart: unless-stopped
volumes:
  vw-data: 
